---
commands:
  - commands: create ltm persistence ssl EXT-OWA_SSL { app-service none defaults-from /Common/ssl match-across-pools disabled match-across-services disabled match-across-virtuals disabled mirror enabled override-connection-limit disabled timeout 300}
monitors_http:
  - objname: "http_mon"
    adaptive: "disabled"
    parent: "/Common/http"
    ip: "*"
    port: "7777"
    interval: "5"
    receive: <head>
    receive_disable: "none"
    send: "GET /sso/pages/index.jsp\r\n"
    time_until_up: "0"
    timeout: "16"
    partition: "Common"
monitors_https:
  - objname: "https_mon"
    adaptive: "disabled"
    cipher_list: "DEFAULT"
    parent: "/Common/https"
    ip: "*"
    port: "*"
    interval: "5"
    receive: none
    receive_disable: "none"
    send: "GET /\r\n"
    ssl_profile: "serverssl"
    time_until_up: "0"
    timeout: "16"
    partition: "Common"
monitors_tcp:
  - objname: "tcp_mon"
    adaptive: "disabled"
    parent: "/Common/tcp"
    ip: "*"
    port: "80"
    interval: "5"
    receive: none
    receive_disable: "none"
    send: none
    time_until_up: "0"
    timeout: "16"
    partition: "Common"
nodes:
  - objname: "10.216.2.90"
    address: "10.216.2.90"
  - objname: "10.240.248.33"
    address: "10.240.248.33"
persists_cookie:
  - objname: "cookie_persist"
    parent: "/Common/cookie"
    partition: "Common"
pools:
  - objname: "http_pool"
    monitors:
      - /Common/http_mon
    partition: "Common"
  - objname: "https_pool"
    monitors:
      - /Common/https_mon
    partition: "Common"
pool_members:
  - poolname: "http_pool"
    aggregate:
      - name: "10.216.2.90"
        port: "80"
        partition: "Common"
        address: "10.216.2.90"
      - name: "10.240.248.33"
        port: "80"
        partition: "Common"
        address: "10.240.248.33"
    partition: "Common"
  - poolname: "https_pool"
    aggregate:
      - name: "10.216.2.90"
        port: "443"
        partition: "Common"
        address: "10.216.2.90"
      - name: "10.240.248.33"
        port: "443"
        partition: "Common"
        address: "10.240.248.33"
    partition: "Common"
profiles_http:
  - objname: "http_profile"
    parent: "http"
    fallback_host: http://mfi.siteupgrade.net/
    proxy_type: "reverse"
    partition: "Common"
profiles_tcp:
  - objname: "tcp_profile"
    close_wait_timeout: "10"
    parent: "/Common/tcp-wan-optimized"
    fin_wait_2_timeout: "600"
    fin_wait_timeout: "10"
    time_wait_timeout: "4000"
    partition: "Common"
profiles_clientssl:
  - objname: "clientssl_profile"
    cert_key_chain:
      - true_names: "no"
        cert: "/Common/default"
        chain: "/Common/ca-bundle"
        key: "/Common/default"
        passphrase: "none"
    parent: "/Common/clientssl"
    partition: "Common"
virtuals:
  - objname: "http_vs"
    destination: "10.244.192.32"
    destport: "80"
    ip_protocol: "tcp"
    mask: "255.255.255.255"
    pool: "http_pool"
    source: "0.0.0.0/0"
    address_translation: "yes"
    port_translation: "yes"
    profiles:
      - /Common/http_profile
      - /Common/tcp_profile
    irules:
      - /Common/_sys_https_redirect
    snat: "automap"
    partition: "Common"
  - objname: "https_vs"
    destination: "10.244.192.32"
    destport: "443"
    ip_protocol: "tcp"
    mask: "255.255.255.255"
    pool: "https_pool"
    source: "0.0.0.0/0"
    address_translation: "yes"
    port_translation: "yes"
    profiles:
      - /Common/http_profile
      - /Common/tcp_profile
      - name: /Common/clientssl_profile
        context: client-side
      - name: /Common/serverssl
        context: server-side
    snat: "automap"
    partition: "Common"