---
# tasks file for create-gtm-wideip.yml

- name: Create GTM WideIP
  f5networks.f5_modules.bigip_gtm_wide_ip:
    name: "{{ gtm_wideip_name }}"
    aliases: "{{ aliases | default(omit) }}"
    irules: "{{ irules | default(omit) }}"
    last_resort_pool: "{{ last_resort_pool | default(omit) }}"
    persist_cidr_ipv4: "{{ persist_cidr_ipv4 | default(omit) }}"
    persist_cidr_ipv6: "{{ persist_cidr_ipv6 | default(omit) }}"
    persistence: "{{ persistence | default(omit) }}"
    persistence_ttl: "{{ persistence_ttl | default(omit) }}"
    pool_lb_method: "{{ pool_lb_method | default(omit) }}"
    pools: "{{ pools | default(omit) }}"
    partition: "{{ partition | default('Common') }}"
    state: "{{ state | default('present') }}"
    type: "{{ type | default(omit) }}"
    provider: "{{provider}}"
