---
- name: Create LDAP Monitor
  hosts: all
  gather_facts: false
  connection: local
  collections:
    - f5networks.f5_modules
  vars_files:
    - bigip-lab.yaml

  vars:
    provider:
      server: 10.4.0.71
      server_port: 443
      validate_certs: no
      user: "{{ user }}"
      password: "{{ password }}"

  tasks:
  - name: Create LDAP Monitor
    bigip_monitor_ldap:
      name: "{{ objname }}"
      base: "{{ base | default('none') }}"
      chase_referrals: "{{ chase_referrals | default('yes') }}"
      debug: "{{ debug | default('no') }}"
      filter: "{{ filter | default('none') }}"
      interval: "{{ interval | default('10') }}"
      mandatory_attributes: "{{ mandatory_attributes | default('none') }}"
      manual_resume: "{{ manual_resume | default('false') }}"
      time_until_up: "{{ time_until_up | default('0') }}"
      timeout: "{{ timeout | default('31') }}"
      parent: "{{ defaults_from | default('/Common/ldap') }}"
      security: "{{ security | default('none') }}"
      provider: "{{ provider }}"
    delegate_to: localhost
