---
- name: Create Pool
  hosts: all
  gather_facts: false
  connection: local
  collections:
    - f5networks.f5_modules

  vars:
    provider:
      server: 10.4.0.71
      server_port: 443
      validate_certs: no
      user: "{{ user }}"
      password: "{{ password }}"

  tasks:
  - name: Create Pool
    bigip_pool:
      name: "{{ objname }}"
      lb_method: "{{ lb_method | default('round-robin') }}"
      monitors: "{{ monitors | default('') }}"
      priority_group_activation: "{{ priority_group_activation | default('0') }}"
      state: "{{ state | default('present') }}"
      provider: "{{ provider }}"
    delegate_to: localhost
