---
- name: Create Clientssl Profile
  hosts: all
  gather_facts: false
  connection: local
  collections:
    - f5networks.f5_modules
  vars_files:
    - bigip-lab.yaml

  vars:
    provider:
      server: 10.4.0.71
      server_port: 443
      validate_certs: no
      user: "{{ user }}"
      password: "{{ password }}"

  tasks:
  - name: Create Clientssl Profile
    bigip_profile_client_ssl:
      name: "{{ objname }}"
      ciphers: "{{ ciphers | default('DEFAULT') }}"
      cipher_group: "{{ cipher_group | default('') }}"
      parent: "{{ parent | default('clientssl') }}"
      cert_key_chain: "{{ cert_key_chain | default('') }}"
      state: "{{ state | default('present') }}"
      provider: "{{ provider }}"
    delegate_to: localhost
