---
- name: Create TCP Monitor
  hosts: all
  gather_facts: false
  connection: local
  collections:
    - f5networks.f5_modules
  vars_files:
    - bigip-lab.yaml

  vars:
    provider:
      server: 10.4.0.71
      server_port: 443
      validate_certs: no
      user: "{{ user }}"
      password: "{{ password }}"

  tasks:
  - name: Create TCP Monitor
    bigip_monitor_tcp:
      name: "{{ objname }}"
      interval: "{{ interval | default('5') }}"
      receive: "{{ receive | default('') }}"
      send: "{{ send | default('') }}"
      time_until_up: "{{ time_until_up | default('0') }}"
      timeout: "{{ timeout | default('16') }}"
      parent: "{{ defaults_from | default('/Common/tcp') }}"
      state: "{{ state | default('present') }}"
      provider: "{{ provider }}"
    delegate_to: localhost
