---
- name: Create HTTP Profile
  hosts: all
  gather_facts: false
  connection: local
  collections:
    - f5networks.f5_modules

  vars:
    provider:
      server: 10.4.0.71
      server_port: 443
      validate_certs: no
      user: "{{ user }}"
      password: "{{ password }}"

  tasks:
  - name: Create HTTP Profile
    bigip_profile_http:
      name: "{{ objname }}"
      insert_xforwarded_for: "{{ insert_xforwarded_for | default('no') }}"
      proxy_type: "{{ proxy_type | default('reverse') }}"
      state: "{{ state | default('present') }}"
      provider: "{{ provider }}"
    delegate_to: localhost
