---
- name: Create Source Address Persistence
  hosts: all
  gather_facts: false
  connection: local
  collections:
    - f5networks.f5_modules
  vars_files:
    - bigip-lab.yaml

  vars:
    provider:
      server: 10.4.0.71
      server_port: 443
      validate_certs: no
      user: "{{ user }}"
      password: "{{ password }}"

  tasks:
  - name: Create Source Address Persistence
    bigip_profile_persistence_src_addr:
      name: "{{ objname }}"
      entry_timeout: "{{ entry_timeout | default('180') }}"
      mask: "{{ mask | default('none') }}"
      match_across_pools: "{{ match_across_pools | default('no') }}"
      match_across_services: "{{ match_across_services | default('no') }}"
      match_across_virtuals: "{{ match_across_virtuals | default('no') }}"
      mirror: "{{ mirror | default('no') }}"
      parent: "{{ parent | default('/Common/source_addr') }}"
      state: "{{ state | default('present') }}"
      provider: "{{ provider }}"
    delegate_to: localhost
