---
- name: creating HTTPS application
  hosts: all
  gather_facts: false

  vars:
    provider:
      server: 10.4.0.71
      server_port: 443
      validate_certs: no
      user: "{{ user }}"
      password: "{{ password }}"


  tasks:
  - name: Create a HTTP node
    bigip_node:
      host: "10.1.10.98"
      name: "http_node"
      provider: "{{ provider }}"
    delegate_to: localhost
