---

- name: Run Commands
  f5networks.f5_modules.bigip_command:
    commands: "{{ item.commands }}"
    provider: "{{ provider }}"
  when: commands is iterable
  loop: "{{ commands | default([], true) }}"
  tags:
    - commands
    - create