---
# tasks file for remove-ltm-irule.yml

- name: Remove iRule
  f5networks.f5_modules.bigip_irule:
    module: "{{ module }}"
    name: "{{ objname }}"
    state: "absent"
    partition: "{{ partition | default('Common') }}"
    provider: "{{ provider }}"
