---
# tasks file for create-ltm-http-monitor.yml

- name: Create HTTP Monitor
  f5networks.f5_modules.bigip_monitor_http:
    name: "{{ objname }}"
    interval: "{{ interval | default('5') }}"
    ip: "{{ ip | default('*') }}"
    port: "{{ port | default('*') }}"
    receive: "{{ receive | default(omit) }}"
    receive_disable: "{{ receive_disable | default(omit) }}"
    send: "{{ send | default(omit) }}"
    target_password: "{{ target_password | default(omit) }}"
    target_username: "{{ target_username | default(omit) }}"
    time_until_up: "{{ time_until_up | default('0') }}"
    timeout: "{{ timeout | default('16') }}"
    parent: "{{ defaults_from | default('/Common/http') }}"
    state: "{{ state | default('present') }}"
    description: "{{ description | default(omit) }}"
    partition: "{{ partition | default('Common') }}"
    provider: "{{ provider }}"
