---

- name: Create ServerSSL Profile
  hosts: all
  connection: netconf
  gather_facts: no

  collections:
    - f5networks.f5_modules

  tasks:
  - name: Create ServerSSL Profile
    include_role:
      name: configure-create-serverssl-profile
  - name: Save Config
    include_role:
      name: save-config
