---

- name: Create Cookie Persistence
  hosts: all
  connection: netconf
  gather_facts: no

  collections:
    - f5networks.f5_modules

  tasks:
  - name: Create Cookie Persistence
    include_role:
      name: configure-create-cookie-persistence
  - name: Save Config
    include_role:
      name: save-config
