---

- name: Remove Gateway ICMP Monitor
  hosts: all
  connection: netconf
  gather_facts: no

  collections:
    - f5networks.f5_modules

  vars_prompt:
  - name: "objname"
    prompt: "Enter Gateway ICMP Monitor Name"
    private: no

  tasks:
  - name: Remove Gateway ICMP Monitor
    include_role:
      name: configure-remove-gateway-icmp-monitor
    
  - name: Save Config
    include_role:
      name: save-config
