---

- name: Create GTM Pool
  hosts: all
  connection: netconf
  gather_facts: no

  collections:
    - f5networks.f5_modules

  tasks:
  - name: Create GTM Pool
    include_role:
      name: configure-create-gtm-pool
  - name: Save Config
    include_role:
      name: save-config
