---

- name: Create Node
  hosts: all
  connection: netconf
  gather_facts: no

  collections:
    - f5networks.f5_modules

  tasks:
  - name: Create Node
    include_role:
      name: configure-create-node
  - name: Save Config
    include_role:
      name: save-config
