---

- name: Create ClientSSL Profile
  hosts: all
  connection: netconf
  gather_facts: no

  collections:
    - f5networks.f5_modules

  tasks:
  - name: Create ClientSSL Profile
    include_role:
      name: configure-create-clientssl-profile
  - name: Save Config
    include_role:
      name: save-config
