---

- name: Create iRule
  hosts: all
  connection: netconf
  gather_facts: no

  collections:
    - f5networks.f5_modules

  tasks:
  - name: Create iRule
    include_role:
      name: configure-create-irule
  - name: Save Config
    include_role:
      name: save-config
