---

- name: Remove LDAP Monitor
  hosts: all
  connection: netconf
  gather_facts: no

  collections:
    - f5networks.f5_modules

  vars_prompt:
  - name: "objname"
    prompt: "Enter LDAP Monitor Name"
    private: no

  tasks:
  - name: Remove LDAP Monitor
    include_role:
      name: configure-remove-ldap-monitor
    
  - name: Save Config
    include_role:
      name: save-config
