---

- name: Create FastL4 Profile
  hosts: all
  connection: netconf
  gather_facts: no

  collections:
    - f5networks.f5_modules

  tasks:
  - name: Create FastL4 Profile
    include_role:
      name: configure-create-fastl4-profile
  - name: Save Config
    include_role:
      name: save-config
