---

- name: Create GTM WideIP
  hosts: all
  connection: netconf
  gather_facts: no

  collections:
    - f5networks.f5_modules

  tasks:
  - name: Create GTM WideIP
    include_role:
      name: configure-create-gtm-wideip
    
  - name: Save Config
    include_role:
      name: save-config
