---

- name: Create DNS Monitor
  hosts: all
  connection: netconf
  gather_facts: no

  collections:
    - f5networks.f5_modules

  tasks:
  - name: Create DNS Monitor
    include_role:
      name: configure-create-dns-monitor
  - name: Save Config
    include_role:
      name: save-config
