---

- name: Remove GTM WideIP
  hosts: all
  connection: netconf
  gather_facts: no

  collections:
    - f5networks.f5_modules

  vars_prompt:
  - name: "gtm_wideip_name"
    prompt: "Enter WideIP Name"
    private: no
  - name: "type"
    prompt: "Enter Type"
    private: no

  tasks:
  - name: Remove GTM WideIP
    include_role:
      name: configure-remove-gtm-wideip
    
  - name: Save Config
    include_role:
      name: save-config
