---

- name: Add Pool Member
  hosts: all
  connection: netconf
  gather_facts: no

  collections:
    - f5networks.f5_modules

  tasks:
  - name: Add Pool Member
    include_role:
      name: configure-add-pool-member
  - name: Save Config
    include_role:
      name: save-config
