---

- name: Create HTTP Monitor
  hosts: all
  connection: netconf
  gather_facts: no

  collections:
    - f5networks.f5_modules

  tasks:
  - name: Create HTTP Monitor
    include_role:
      name: configure-create-http-monitor
  - name: Save Config
    include_role:
      name: save-config
